--- CMakeModules/nel.cmake.orig	2022-06-01 11:49:50 UTC
+++ CMakeModules/nel.cmake
@@ -410,7 +410,7 @@ MACRO(ADD_PLATFORM_FLAGS _FLAGS)
 ENDMACRO()
 
 MACRO(ADD_PLATFORM_LINKFLAGS _FLAGS)
-  SET(PLATFORM_LINKFLAGS "${PLATFORM_LINKFLAGS} ${_FLAGS}")
+  SET(PLATFORM_LINKFLAGS "${PLATFORM_LINKFLAGS} ${_FLAGS} -lexecinfo")
 ENDMACRO()
 
 MACRO(CONVERT_VERSION_NUMBER _VERSION_NUMBER _BASE)
